### ISSUE TITLE
**I am trying many times but got this error.**

### ISSUE THREAD

**Issue by vijayrajpanchall** [kshsri21/NFT-#1]
C:\Users\Admin\Desktop\blockchain\ERC721>npx hardhat compile
Error HH8: There's one or more errors in your config file:

  * Invalid value undefined for HardhatConfig.networks.ropsten.url - Expected a value of type string.
  * Invalid account: #0 for network: ropsten - private key too short, expected 32 bytes

To learn more about Hardhat's configuration, please go to https://hardhat.org/config/

**Comment by bappirahman** [comment]
did you used dotenv package I think you didn't used it that's why you're getting error for url & private key

**Comment by kpganvir** [comment]
.env file is not in root directory..i hope its already been solved.

**Comment by Boggiefottie** [comment]
ropsten has been depreciated
